import './globals.css';
import { Inter } from 'next/font/google';
import { MainMenu } from '../components/menu';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainMenu />
        <main className="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
          {children}
        </main>
      </body>
    </html>
  );
}
